spring:
  redis:
    host: localhost
    port: 6379
    password: 123456

sharding:
  jdbc:
    datasource:
      names: ds-master,ds-slave-0,ds-slave-1
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://localhost:3306/jww?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      ds-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://localhost:3306/jww?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      ds-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://localhost:3306/jww?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    config:
      masterslave:
        name: ds
        masterDataSourceName: ds-master
        slaveDataSourceNames: [ds-slave-0,ds-slave-1]
        loadBalanceAlgorithmType: round_robin

swagger:
  api:
    enabled: true
    name: Jww Name
    title: Jww Title
    description: Jww Description
    version: 2.0.0
    contactUser: Jww User
    contactUrl: Jww Url
    contactEmail: Jww Email