spring:
  redis:
    host: 119.29.114.28
    port: 6379
    password: Jww~0731520

sharding:
  jdbc:
    datasource:
      names: ds-master,ds-slave-0,ds-slave-1
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Jww~0731520
        jdbc-url: jdbc:mysql://119.29.114.28:3306/jww?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      ds-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Jww~0731520
        jdbc-url: jdbc:mysql://119.29.114.28:3306/jww?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      ds-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Jww~0731520
        jdbc-url: jdbc:mysql://119.29.114.28:3306/jww?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    config:
      masterslave:
        name: ds
        masterDataSourceName: ds-master
        slaveDataSourceNames: [ds-slave-0,ds-slave-1]
        loadBalanceAlgorithmType: round_robin

swagger:
  api:
    enabled: true
    name: Jww
    title: Jww Swagger Api
    description: Jww接口文档
    version: 2.0.0
    contactUser: Jww
    contactUrl: http://www.jww.com
    contactEmail: admin@jww.com